---
title: Shreya Gupta
---
description: Hi! I have worked for 2+ years. After one year of gap year, I
  decided to transition to Data Analysis.<br> I've worked as an Intern, Junior
  Developer, Senior Developer and Technical Lead in a product oriented edtech
  startup, Cerebry.I've also worked as an Intern at WNS, Gurgaon India.
  <br>I hold a Bachelor's of Technology (B.Tech) degree in Computer
  Science. <br><br>I love to read books (My favorite is I am the Messenger by
  Markus Zusak, the ending!), sketching and travelling.
git_url: https://github.com/gshreya5
mail_url: mailto:shreyagupta5432@gmail.com
linkedin_url: https://www.linkedin.com/in/shreya-gupta-sg/
theme: jekyll-theme-minimal
